version: "3.8"
services:
  frontend:
    build: ./frontend
    image: ghcr.io/hanna-kath/deployment-assignment-hanna-kath:latest
    ports:
      - "80:80"
  backend:
    build: ./backend
  mariadb:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: mis
      MARIADB_USER: mis
      MARIADB_PASSWORD: mis
    ports:
      - "33306:3306"